---
title: Best Practices
author: Paul Schrimpf
date: last-modified
bibliography: 622.bib
execute:
  eval: false
  echo: true
  cache: true
  freeze: auto
format:
  revealjs:
    theme: night
    smaller: true
    min-scale: 0.1
    max-scale: 3.0
    chalkboard:
      theme: whiteboard
      boardmarker-width: 2
      chalk-width: 2
      chalk-effect: 0.0
engine: julia
---

$$
\def\Er{{\mathrm{E}}}
\def\En{{\mathbb{E}_n}}
\def\cov{{\mathrm{Cov}}}
\def\var{{\mathrm{Var}}}
\def\R{{\mathbb{R}}}
\def\arg{{\mathrm{arg}}}
\newcommand\norm[1]{\left\lVert#1\right\rVert}
\def\rank{{\mathrm{rank}}}
\newcommand{\inpr}{ \overset{p^*_{\scriptscriptstyle n}}{\longrightarrow}}
\def\inprob{{\,{\buildrel p \over \rightarrow}\,}}
\def\indist{\,{\buildrel d \over \rightarrow}\,}
\DeclareMathOperator*{\plim}{plim}
\DeclareMathOperator*{\argmax}{argmax}
\DeclareMathOperator*{\argmin}{argmin}
$$

# Overview

## Goals

- Correct
- Maintainable & Extensible
  - Clear
  - Contained
  - Consistent
- Efficient


## Tools

| Goal | Tool(s) |
|------|---------|
|Correct | tests, static analysis |
|Maintainable | version control, CI, documentation, dependency management |
|Efficient | benchmarks, profiler |


# Version Control

## Version Control

- essential
- git is by far the most popular and what I recommend
- git hosting services
  - github.com
  - gitlab.com
  - bitbucket.org
- Benefits:
  - backup
  - edit history
  - coordination

## git

- Use it
- [git intro and tutorial](https://mint.westdri.ca/git/intro_intro) and [webinar recording](https://www.youtube.com/watch?v=nulmjJq5Fz0)
  - [Intro course on March 5](https://docs.google.com/forms/d/e/1FAIpQLSf0eYiXCPvhql1Ql2icoZHjs5sbLzLJwevDH0LqgouvAdfL8A/viewform) and [follow-up course on March 10](https://docs.google.com/forms/d/e/1FAIpQLSdNrWmVg9xV-zZ0q-dg7uVhQi34Y6f4X201qfdk68cRnV5K1w/viewform)


# Julia Tools

## Create Packages

- Organize code into a package
  - enables: testing, Revise.jl, version control, code reuse, distribution, etc
- Good advice aimed at scientific computing projects: [Julia: Project Workflow](https://j-fu.github.io/marginalia/julia/project-workflow/)
- Setup your package with a project skeleton
  - [`BestieTemplate.jl`](https://github.com/abelsiqueira/BestieTemplate.jl)
  - [`PkgTemplates.jl`](https://github.com/JuliaCI/PkgTemplates.jl)
  - [`DoctorWatson.jl`](https://juliadynamics.github.io/DrWatson.jl/stable/)
  - @haider2021 for similar idea for other languages

## PkgTemplates.jl

```{julia}
#| eval: false
using PkgTemplates
Template(interactive=true)("SomeNewPackage")
```

or

```{julia}
using PkgTemplates
tpl = Template(; dir=pwd(),
               user="schrimpf", # github username
               authors=["Paul Schrimpf"],
               plugins=[ProjectFile(), SrcDir(),
                        Tests(project=true, aqua=true, jet=true),
                        License(; name="MIT"),
                        Git(),
                        GitHubActions(),
                        Codecov(),
                        Citation(),
                        Documenter{GitHubActions}(),
                        PkgBenchmark(),
                        Formatter()]
               )
tpl("SomeNewPackage")
```

```{julia}
#| echo: false
rm("SomeNewPackage", recursive=true)
```

## BestieTemplate.jl

```{julia}
#| eval: false
using BestieTemplate
BestieTemplate.generate("TestPackage")
```


## Dependencies and Where to Install Them

- In the default/global project: (reached by `activate` in pkg mode) put utilities that you always want available
- In each project environment (i.e. `activate .` when in TestPackage directory) put dependencies that are required for the re-usable code in the package in `TestPackage/src`
- Some dependencies are required for a task, like running tests or creating documents, but not strictly needed for everything a package might be used for these go in an environment in `TestPackage/test` or `TestPackage/docs`
  - Or edit `TestPackage/Project.toml` as described in the [Pkg docs](https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies)

## My Default Project

```{julia}
#| eval: false
(@v1.12) pkg> activate
  Activating project at `~/.julia/environments/v1.12`
(@v1.12) pkg> st
Status `~/.julia/environments/v1.12/Project.toml`
  [6e4b80f9] BenchmarkTools v1.6.3
  [31a5f54b] Debugger v0.7.16
  [b2ad6718] EmacsVterm v0.3.0
  [7073ff75] IJulia v1.34.4
  [5903a43b] Infiltrator v1.9.7
  [5fb14364] OhMyREPL v0.5.32
  [295af30f] Revise v3.13.2
  [0c614874] TerminalPager v0.6.10 [loaded: v0.6.9]
```


## Tests

- essential
- organize code into small functions, test them all
- test both your code and code from others that you rely on
- use either [standard library `Tests`](https://docs.julialang.org/en/v1/stdlib/Test/)
  or [`TestItems.jl`](https://www.julia-vscode.org/docs/stable/userguide/testitems/) (good VS Code integration)

## Documentation

- create it for others and your future self
- at least [doc strings](https://docs.julialang.org/en/v1/manual/documentation/)
- use [Documenter.jl](https://documenter.juliadocs.org/stable/) to generate html documentation

## Continuous Integration

- Automatically execute some actions in the cloud after git commits or pull requests or merges
  - Run tests
  - Build documentation
  - Run static code analysis / Linter
  - Check test coverage
  - etc
- Many providers
  - GitHub Actions
  - TravisCI
  - etc

## Test Coverage

- Automatically try to determine which lines of code were executed during testing and produce a summary and report
- app.codecov.io
- coveralls.io

## Static Code Analysis

- "linters" analyze code to detect errors and possible bugs
  - built into VSCode and other editors
  - JET.jl for detecting type stability problems (advanced)
- formatters check for following text formatting standards around indentation and such

## Debugging

- adding `println`, `@show`, or similar is an okay starting point
- `Infiltrator.jl` and `Debugger.jl` lets you halt execution anywhere and examine variables
   - [MoJuWo on debugging](https://modernjuliaworkflows.org/writing/#debugging)

## Further Reading

- @gentzkow2014
- @pruim2023
- @wilson2017
- @haider2021
- @orozco2020


## References
